# prometheus-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.33.1
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/data'
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-data1
              mountPath: /data
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
          securityContext:
            runAsUser: 0
            fsGroup: 0  
      volumes:
        - name: prometheus-data1
          persistentVolumeClaim:
            claimName: prometheus-data1
        - name: prometheus-config
          configMap:
            name: prometheus-config
